# Travis CI(http://travis-ci.org) configuration file
language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2" Sphinx depends on Pygments, which only supports Python 3.3+
  - "3.3"
  - "3.4"

before_install:
  # Update APT cache data since it may outdated
  - sudo apt-get -qq update
  # according to Debian control file from Ubuntu 12.04
  - sudo apt-get install -y git rsync gettext
  # Git test setup
  - git config --global user.name "Git Cola"
  - git config --global user.email git-cola@localhost.localdomain

# command to install dependencies, git and python are pre-installed in build box thus are ignored
install:
  # SIP
  - mkdir -p local/sandbox
  - cd local/sandbox
  - wget "http://sourceforge.net/projects/pyqt/files/sip/sip-4.18.1/sip-4.18.1.tar.gz"
  - tar xzf sip-4.18.1.tar.gz
  - cd sip-4.18.1
  - python configure.py --incdir="$(python -c 'import sys; print(sys.prefix)')"/include/python"$PYTHON_VERSION"
  - make -j4
  - make install
  - cd ..
  # PyQt4
  - wget "http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz"
  - tar xzf PyQt-x11-gpl-4.11.4.tar.gz
  - cd PyQt-x11-gpl-4.11.4
  - python configure.py --confirm-license --no-designer-plugin --no-qsci-api --no-timestamp
  - make -j4
  - make install
  - cd ../../..
  # Pylint
  - pip install astroid==1.4.3
  - pip install pylint==1.5.2
  # Build dependencies
  - make requirements
  # Test dependencies
  - make requirements-dev

script:
  - make all
  # Sphinx requires Python 3.4
  - test "2.6" = "$TRAVIS_PYTHON_VERSION" || test "3.3" = "$TRAVIS_PYTHON_VERSION" || make doc
  # TODO tests currently fail on Python3 due to sip
  - env GIT_COLA_NO_HISTORY=1 make test flags=--verbose
  # pylint 1.4 uses python2.7+ syntax so skip pylint on python2.6
  - test "2.6" = "$TRAVIS_PYTHON_VERSION" || make pylint3k
